defmodule CairnloopExampleWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :cairnloop_example

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_cairnloop_example_key",
    signing_salt: "mCLo6ezw",
    same_site: "Lax"
  ]

  # `:user_agent` is declared so browser E2E (phoenix_test_playwright) can ship Ecto-sandbox
  # metadata in the User-Agent header and have the LiveView process join the shared test
  # connection (see CairnloopExampleWeb.LiveAcceptance + the :sql_sandbox-gated plug below).
  # Harmless in dev/prod — it's just an exposed connect_info key.
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:user_agent, session: @session_options]],
    longpoll: [connect_info: [:user_agent, session: @session_options]]

  # Phase 28 D-15: mount the widget channel transport at /widget.
  # WebSocket-only (longpoll: false) — the widget is a single-tab browser UI;
  # longpoll fallback adds latency and is not needed for demo mode.
  # WidgetSocket reads its token from params["token"], NOT from the Plug session,
  # so connect_info is omitted here (see widget_socket.ex:10-13).
  socket "/widget", Cairnloop.Channels.WidgetSocket,
    websocket: true,
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :cairnloop_example,
    gzip: not code_reloading?,
    only: CairnloopExampleWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :cairnloop_example
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # Browser E2E only (test env, `config :cairnloop_example, :sql_sandbox, true`): allow the HTTP
  # request process (the LiveView dead-render mount) to join the test's shared Ecto sandbox
  # connection, reading the metadata phoenix_test_playwright sends in the User-Agent header.
  # Compiled out entirely in dev/prod.
  if Application.compile_env(:cairnloop_example, :sql_sandbox) do
    plug Phoenix.Ecto.SQL.Sandbox
  end

  plug CairnloopExampleWeb.Router
end
