import Config

# Configure your database
config :cairnloop_example, CairnloopExample.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "cairnloop_example_dev",
  # Honor PGPORT (matches docker-compose.yml + the library's config/test.exs) so the
  # demo DB port is overridable without editing config. Defaults to 5433.
  port: String.to_integer(System.get_env("PGPORT") || "5433"),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Chimeway (a transitive Cairnloop dependency) unconditionally starts its own Repo. The demo
# doesn't use it, but without a database it floods the dev log (and the browser console, via
# LiveView dev log forwarding) with "missing the :database key" errors. Point it at the demo DB
# so it connects quietly and stays idle.
config :chimeway, Chimeway.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "cairnloop_example_dev",
  port: String.to_integer(System.get_env("PGPORT") || "5433"),
  pool_size: 2

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :cairnloop_example, CairnloopExampleWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  # Honor PORT (default 4000) so the demo can sidestep a port already in use.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "toRX4Kr+2AHLpJr5bTeiK39tVP6RDPf4K3X5ajaXWf02C8mg5rODatgbm7zWUom3",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:cairnloop_example, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:cairnloop_example, ~w(--watch)]}
  ]

config :cairnloop, Cairnloop.KnowledgeAutomation.EditorHandoff,
  secret_key_base: "dev_only_64_byte_minimum_secret_for_editor_handoff_tokens_cairnloop"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :cairnloop_example, CairnloopExampleWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/cairnloop_example_web/router\.ex$"E,
      ~r"lib/cairnloop_example_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :cairnloop_example, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
