defmodule Cairnloop.Integration.ToolExecutionWorkerTest do
  @moduledoc """
  Integration coverage for Phase 16 (ACT-01): the end-to-end execution worker flow
  against real Postgres. Verifies that a governed tool proposal approved through the
  `:execution_pending` lane is picked up by `ToolExecutionWorker`, which calls `run/3`
  exactly once, co-commits the outcome (`:executed` + `:succeeded` result), and writes
  exactly one `cairnloop_messages` row.

  Cairnloop ships no Oban migration (the host owns oban_jobs), so we exercise the workers
  directly via `perform/1` rather than through a running Oban instance — the DB transitions
  are real.

  All assertions in this file require a Postgres round-trip.
  # REPO-UNAVAILABLE — only runs under `MIX_ENV=test mix test.integration` (dockerized pgvector).
  """
  use Cairnloop.DataCase, async: false

  alias Cairnloop.Governance
  alias Cairnloop.Governance.{ToolApproval, ToolProposal}
  alias Cairnloop.Message
  alias Cairnloop.Workers.{ApprovalResumeWorker, ToolExecutionWorker}

  import Cairnloop.Fixtures

  # ---------------------------------------------------------------------------
  # Inline NoteWriteTool — mirrors PassTool in approval_flow_test.exs (lines 20-41).
  # A minimal governed-write tool whose run/3 inserts a cairnloop_messages row.
  # The real InternalNote does the same; we use a local module so the test controls
  # the run/3 behaviour precisely.
  # ---------------------------------------------------------------------------
  defmodule NoteWriteTool do
    use Cairnloop.Tool,
      risk_tier: :low_write,
      title: "Note Write Tool",
      description: "Test tool that writes an internal note."

    embedded_schema do
      field(:conversation_id, :string)
      field(:content, :string)
    end

    @impl Cairnloop.Tool
    def changeset(struct, attrs) do
      import Ecto.Changeset
      struct |> cast(attrs, [:conversation_id, :content])
    end

    @impl Cairnloop.Tool
    def scope, do: []

    @impl Cairnloop.Tool
    def authorize(_actor_id, _context), do: :ok

    @impl Cairnloop.Tool
    def run(%__MODULE__{conversation_id: conv_id, content: content}, _actor_id, context) do
      repo = Application.fetch_env!(:cairnloop, :repo)
      run_key = Map.get(context, :run_idempotency_key)

      # Idempotency: indexed run_key existence check (D16-05)
      # NEVER: repo.get_by(Message, metadata: %{run_key: run_key}) — JSONB @> not generated by Ecto
      case run_key && repo.get_by(Cairnloop.Message, run_key: run_key) do
        %Cairnloop.Message{} ->
          {:ok, %{idempotent: true}}

        _ ->
          attrs = %{
            conversation_id: conv_id,
            content: content || "test note",
            role: :internal_note,
            run_key: run_key,
            metadata: %{source: "cairnloop_governed_action", run_key: run_key}
          }

          case repo.insert(Cairnloop.Message.changeset(%Cairnloop.Message{}, attrs)) do
            {:ok, msg} -> {:ok, %{message_id: msg.id}}
            {:error, cs} -> {:error, cs}
          end
      end
    end
  end

  setup do
    Application.put_env(:cairnloop, :tools, [NoteWriteTool])
    on_exit(fn -> Application.delete_env(:cairnloop, :tools) end)
    :ok
  end

  # ---------------------------------------------------------------------------
  # Happy path: approved lane → ToolExecutionWorker → :executed + 1 message row
  # ---------------------------------------------------------------------------

  test "happy path: :execution_pending → :executed writes exactly one internal_note row" do
    test_pid = self()
    capture = fn job -> send(test_pid, {:enqueued, job}); {:ok, job} end

    proposal =
      proposal_fixture(%{
        tool_ref: Atom.to_string(NoteWriteTool),
        approval_mode: :requires_approval,
        scope_snapshot: %{scopes: []},
        input_snapshot: %{conversation_id: "conv-001", content: "hello"}
      })

    # Open the approval lane
    assert {:ok, approval} = Governance.request_approval(proposal, enqueue_fn: capture)

    # Approve: transitions :pending → :approved
    assert {:ok, _approved} = Governance.approve(approval.id, "operator_1", enqueue_fn: capture)

    # Resume worker: transitions :approved → :execution_pending (does NOT call run/3)
    assert :ok = ApprovalResumeWorker.perform(%Oban.Job{args: %{"approval_id" => approval.id}})
    assert Repo.get!(ToolApproval, approval.id).status == :execution_pending

    # Execution worker: re-validates, calls run/3, co-commits outcome
    assert :ok =
             ToolExecutionWorker.perform(%Oban.Job{
               attempt: 1,
               max_attempts: 3,
               args: %{"approval_id" => approval.id}
             })

    # Assertions (require Postgres round-trip)
    # REPO-UNAVAILABLE: the lines below only pass under mix test.integration

    updated_approval = Repo.get!(ToolApproval, approval.id)
    assert updated_approval.status == :executed

    updated_proposal = Repo.get!(ToolProposal, proposal.id)
    assert updated_proposal.result_state == :succeeded
    assert updated_proposal.attempt == 1

    # Exactly one internal_note message row
    assert Repo.aggregate(Message, :count) == 1
    [msg] = Repo.all(Message)
    assert msg.role == :internal_note
  end

  # ---------------------------------------------------------------------------
  # Idempotency: replaying a completed job is a terminal no-op (T-16-01)
  # ---------------------------------------------------------------------------

  test "replaying an :executed approval is an idempotent no-op — no second message row" do
    test_pid = self()
    capture = fn job -> send(test_pid, {:enqueued, job}); {:ok, job} end

    proposal =
      proposal_fixture(%{
        tool_ref: Atom.to_string(NoteWriteTool),
        approval_mode: :requires_approval,
        scope_snapshot: %{scopes: []},
        input_snapshot: %{conversation_id: "conv-002", content: "replay test"}
      })

    assert {:ok, approval} = Governance.request_approval(proposal, enqueue_fn: capture)
    assert {:ok, _approved} = Governance.approve(approval.id, "operator_1", enqueue_fn: capture)
    assert :ok = ApprovalResumeWorker.perform(%Oban.Job{args: %{"approval_id" => approval.id}})

    # First execution
    assert :ok =
             ToolExecutionWorker.perform(%Oban.Job{
               attempt: 1,
               max_attempts: 3,
               args: %{"approval_id" => approval.id}
             })

    # REPO-UNAVAILABLE: assertions below only pass under mix test.integration
    assert Repo.get!(ToolApproval, approval.id).status == :executed

    # Replay — must be a no-op
    assert :ok =
             ToolExecutionWorker.perform(%Oban.Job{
               attempt: 2,
               max_attempts: 3,
               args: %{"approval_id" => approval.id}
             })

    # Still exactly one message row — run/3 was not called a second time
    assert Repo.aggregate(Message, :count) == 1
  end

  # ---------------------------------------------------------------------------
  # Terminal guard: wrong status is an idempotent no-op (T-16-01, layer 1)
  # ---------------------------------------------------------------------------

  test "perform/1 on a non-:execution_pending approval is an idempotent :ok" do
    proposal =
      proposal_fixture(%{
        tool_ref: Atom.to_string(NoteWriteTool),
        approval_mode: :requires_approval
      })

    test_pid = self()
    capture = fn job -> send(test_pid, {:enqueued, job}); {:ok, job} end

    assert {:ok, approval} = Governance.request_approval(proposal, enqueue_fn: capture)
    # approval is still :pending — execution worker must be a no-op

    assert :ok =
             ToolExecutionWorker.perform(%Oban.Job{
               attempt: 1,
               max_attempts: 3,
               args: %{"approval_id" => approval.id}
             })

    # REPO-UNAVAILABLE: assertions below only pass under mix test.integration
    # Status must remain :pending — nothing written
    assert Repo.get!(ToolApproval, approval.id).status == :pending
    assert Repo.aggregate(Message, :count) == 0
  end

  # ---------------------------------------------------------------------------
  # Terminal guard: nil approval is an idempotent no-op
  # ---------------------------------------------------------------------------

  test "perform/1 with a non-existent approval_id is a silent :ok no-op" do
    assert :ok =
             ToolExecutionWorker.perform(%Oban.Job{
               attempt: 1,
               max_attempts: 3,
               args: %{"approval_id" => 0}
             })
  end

  # ---------------------------------------------------------------------------
  # TODO (Plans 02/03): additional coverage rows from VALIDATION.md
  #
  # - T-16-02: re-validation failure at execution time fails closed → :invalidated/:execution_failed
  #   (test: force expires_at in the past after :execution_pending)
  # - T-16-01 (at-most-once): run_key idempotency prevents double-write under concurrent replays
  #   (test: call run/3 twice with same run_key; assert still 1 row)
  # - D16-07 transient: attempt < max_attempts → {:error, reason} so Oban retries
  #   (test: inject a run/3 that returns {:error, :db_hiccup}; assert attempt incremented +
  #    :execution_attempt_failed event; assert {:error, _} returned so Oban retries)
  # - D16-07 terminal: attempt >= max_attempts → {:cancel, reason} + :execution_failed
  # - OBS-02: telemetry labels carry no actor_id/conversation_id/account_id
  #   (test: attach telemetry handler; assert refute Map.has_key?(meta, :actor_id))
  # - D16-10: [:cairnloop, :governance, :action_executed] emitted after co-commit
  # ---------------------------------------------------------------------------
end
