defmodule Cairnloop.Integration.ToolExecutionWorkerTest do
  @moduledoc """
  Integration coverage for Phase 16 (ACT-01): the end-to-end execution worker flow
  against real Postgres. Verifies that a governed tool proposal approved through the
  `:execution_pending` lane is picked up by `ToolExecutionWorker`, which calls `run/3`
  exactly once, co-commits the outcome (`:executed` + `:succeeded` result), and writes
  exactly one `cairnloop_messages` row.

  Cairnloop ships no Oban migration (the host owns oban_jobs), so we exercise the workers
  directly via `perform/1` rather than through a running Oban instance — the DB transitions
  are real.

  All assertions in this file require a Postgres round-trip.
  # REPO-UNAVAILABLE — only runs under `MIX_ENV=test mix test.integration` (dockerized pgvector).
  """
  use Cairnloop.DataCase, async: false

  alias Cairnloop.Governance
  alias Cairnloop.Governance.{ToolApproval, ToolProposal}
  alias Cairnloop.Message
  alias Cairnloop.Workers.{ApprovalResumeWorker, ToolExecutionWorker}

  import Cairnloop.Fixtures

  # ---------------------------------------------------------------------------
  # Inline NoteWriteTool — mirrors PassTool in approval_flow_test.exs (lines 20-41).
  # A minimal governed-write tool whose run/3 inserts a cairnloop_messages row.
  # The real InternalNote does the same; we use a local module so the test controls
  # the run/3 behaviour precisely.
  # ---------------------------------------------------------------------------
  defmodule NoteWriteTool do
    use Cairnloop.Tool,
      risk_tier: :low_write,
      title: "Note Write Tool",
      description: "Test tool that writes an internal note."

    embedded_schema do
      field(:conversation_id, :string)
      field(:content, :string)
    end

    @impl Cairnloop.Tool
    def changeset(struct, attrs) do
      import Ecto.Changeset
      struct |> cast(attrs, [:conversation_id, :content])
    end

    @impl Cairnloop.Tool
    def scope, do: []

    @impl Cairnloop.Tool
    def authorize(_actor_id, _context), do: :ok

    @impl Cairnloop.Tool
    def run(%__MODULE__{conversation_id: conv_id, content: content}, _actor_id, context) do
      repo = Application.fetch_env!(:cairnloop, :repo)
      run_key = Map.get(context, :run_idempotency_key)

      # Idempotency: indexed run_key existence check (D16-05)
      # NEVER: repo.get_by(Message, metadata: %{run_key: run_key}) — JSONB @> not generated by Ecto
      case run_key && repo.get_by(Cairnloop.Message, run_key: run_key) do
        %Cairnloop.Message{} ->
          {:ok, %{idempotent: true}}

        _ ->
          attrs = %{
            conversation_id: conv_id,
            content: content || "test note",
            role: :internal_note,
            run_key: run_key,
            metadata: %{source: "cairnloop_governed_action", run_key: run_key}
          }

          case repo.insert(Cairnloop.Message.changeset(%Cairnloop.Message{}, attrs)) do
            {:ok, msg} -> {:ok, %{message_id: msg.id}}
            {:error, cs} -> {:error, cs}
          end
      end
    end
  end

  setup do
    Application.put_env(:cairnloop, :tools, [NoteWriteTool])
    on_exit(fn -> Application.delete_env(:cairnloop, :tools) end)
    :ok
  end

  # ---------------------------------------------------------------------------
  # Happy path: approved lane → ToolExecutionWorker → :executed + 1 message row
  # ---------------------------------------------------------------------------

  test "happy path: :execution_pending → :executed writes exactly one internal_note row" do
    test_pid = self()

    capture = fn job ->
      send(test_pid, {:enqueued, job})
      {:ok, job}
    end

    proposal =
      proposal_fixture(%{
        tool_ref: Atom.to_string(NoteWriteTool),
        approval_mode: :requires_approval,
        scope_snapshot: %{scopes: []},
        input_snapshot: %{conversation_id: "conv-001", content: "hello"}
      })

    # Open the approval lane
    assert {:ok, approval} = Governance.request_approval(proposal, enqueue_fn: capture)

    # Approve: transitions :pending → :approved
    assert {:ok, _approved} = Governance.approve(approval.id, "operator_1", enqueue_fn: capture)

    # Resume worker: transitions :approved → :execution_pending (does NOT call run/3)
    assert :ok = ApprovalResumeWorker.perform(%Oban.Job{args: %{"approval_id" => approval.id}})
    assert Repo.get!(ToolApproval, approval.id).status == :execution_pending

    # Execution worker: re-validates, calls run/3, co-commits outcome
    assert :ok =
             ToolExecutionWorker.perform(%Oban.Job{
               attempt: 1,
               max_attempts: 3,
               args: %{"approval_id" => approval.id}
             })

    # Assertions (require Postgres round-trip)
    # REPO-UNAVAILABLE: the lines below only pass under mix test.integration

    updated_approval = Repo.get!(ToolApproval, approval.id)
    assert updated_approval.status == :executed

    updated_proposal = Repo.get!(ToolProposal, proposal.id)
    assert updated_proposal.result_state == :succeeded
    assert updated_proposal.attempt == 1

    # Exactly one internal_note message row
    assert Repo.aggregate(Message, :count) == 1
    [msg] = Repo.all(Message)
    assert msg.role == :internal_note
  end

  # ---------------------------------------------------------------------------
  # Idempotency: replaying a completed job is a terminal no-op (T-16-01)
  # ---------------------------------------------------------------------------

  test "replaying an :executed approval is an idempotent no-op — no second message row" do
    test_pid = self()

    capture = fn job ->
      send(test_pid, {:enqueued, job})
      {:ok, job}
    end

    proposal =
      proposal_fixture(%{
        tool_ref: Atom.to_string(NoteWriteTool),
        approval_mode: :requires_approval,
        scope_snapshot: %{scopes: []},
        input_snapshot: %{conversation_id: "conv-002", content: "replay test"}
      })

    assert {:ok, approval} = Governance.request_approval(proposal, enqueue_fn: capture)
    assert {:ok, _approved} = Governance.approve(approval.id, "operator_1", enqueue_fn: capture)
    assert :ok = ApprovalResumeWorker.perform(%Oban.Job{args: %{"approval_id" => approval.id}})

    # First execution
    assert :ok =
             ToolExecutionWorker.perform(%Oban.Job{
               attempt: 1,
               max_attempts: 3,
               args: %{"approval_id" => approval.id}
             })

    # REPO-UNAVAILABLE: assertions below only pass under mix test.integration
    assert Repo.get!(ToolApproval, approval.id).status == :executed

    # Replay — must be a no-op
    assert :ok =
             ToolExecutionWorker.perform(%Oban.Job{
               attempt: 2,
               max_attempts: 3,
               args: %{"approval_id" => approval.id}
             })

    # Still exactly one message row — run/3 was not called a second time
    assert Repo.aggregate(Message, :count) == 1
  end

  # ---------------------------------------------------------------------------
  # Terminal guard: wrong status is an idempotent no-op (T-16-01, layer 1)
  # ---------------------------------------------------------------------------

  test "perform/1 on a non-:execution_pending approval is an idempotent :ok" do
    proposal =
      proposal_fixture(%{
        tool_ref: Atom.to_string(NoteWriteTool),
        approval_mode: :requires_approval
      })

    test_pid = self()

    capture = fn job ->
      send(test_pid, {:enqueued, job})
      {:ok, job}
    end

    assert {:ok, approval} = Governance.request_approval(proposal, enqueue_fn: capture)
    # approval is still :pending — execution worker must be a no-op

    assert :ok =
             ToolExecutionWorker.perform(%Oban.Job{
               attempt: 1,
               max_attempts: 3,
               args: %{"approval_id" => approval.id}
             })

    # REPO-UNAVAILABLE: assertions below only pass under mix test.integration
    # Status must remain :pending — nothing written
    assert Repo.get!(ToolApproval, approval.id).status == :pending
    assert Repo.aggregate(Message, :count) == 0
  end

  # ---------------------------------------------------------------------------
  # Terminal guard: nil approval is an idempotent no-op
  # ---------------------------------------------------------------------------

  test "perform/1 with a non-existent approval_id is a silent :ok no-op" do
    assert :ok =
             ToolExecutionWorker.perform(%Oban.Job{
               attempt: 1,
               max_attempts: 3,
               args: %{"approval_id" => 0}
             })
  end

  # ===========================================================================
  # Plan 02 / Task 3: DB-backed at-most-once / retry / idempotency proof
  # ===========================================================================

  # ---------------------------------------------------------------------------
  # Inline FailOnceTool — returns {:error, :db_hiccup} on the first call per
  # test process, then {:ok, %{}} on subsequent calls. Uses the process
  # dictionary to track invocation count so successive perform/1 calls in the
  # same test simulate transient-then-success retry semantics.
  # ---------------------------------------------------------------------------
  defmodule FailOnceTool do
    use Cairnloop.Tool,
      risk_tier: :low_write,
      title: "Fail Once Tool",
      description: "Returns {:error, reason} on first call, {:ok, %{}} thereafter."

    embedded_schema do
      field(:conversation_id, :string)
    end

    @impl Cairnloop.Tool
    def changeset(struct, attrs) do
      import Ecto.Changeset
      struct |> cast(attrs, [:conversation_id])
    end

    @impl Cairnloop.Tool
    def scope, do: []

    @impl Cairnloop.Tool
    def authorize(_actor_id, _context), do: :ok

    @impl Cairnloop.Tool
    def run(%__MODULE__{}, _actor_id, _context) do
      # Track call count in the agent's process dictionary (test-local)
      count = Process.get({__MODULE__, :call_count}, 0)
      Process.put({__MODULE__, :call_count}, count + 1)

      if count == 0 do
        {:error, :db_hiccup}
      else
        {:ok, %{retried: true}}
      end
    end
  end

  setup :setup_fail_once_tool

  defp setup_fail_once_tool(_) do
    existing = Application.get_env(:cairnloop, :tools, [])
    Application.put_env(:cairnloop, :tools, Enum.uniq(existing ++ [FailOnceTool]))
    on_exit(fn -> Application.put_env(:cairnloop, :tools, existing) end)
    :ok
  end

  # ---------------------------------------------------------------------------
  # at-most-once write: two perform/1 with the same approval_id produce ONE row
  # (T-16-01, D16-05 layer 3 + run/3 idempotency key)
  #
  # This test exercises the FULL at-most-once stack: the LAYER-2 terminal guard
  # (result_state == :succeeded) prevents re-entry into execute_tool/5, so the
  # second perform/1 never calls run/3 and thus no second Message row is written.
  #
  # REPO-UNAVAILABLE: Repo.aggregate and Repo.get! require a Postgres round-trip;
  # only passes under `MIX_ENV=test mix test.integration`.
  # ---------------------------------------------------------------------------

  test "at-most-once: two perform/1 calls with same approval_id write exactly one message row" do
    test_pid = self()

    capture = fn job ->
      send(test_pid, {:enqueued, job})
      {:ok, job}
    end

    proposal =
      proposal_fixture(%{
        tool_ref: Atom.to_string(NoteWriteTool),
        approval_mode: :requires_approval,
        scope_snapshot: %{scopes: []},
        input_snapshot: %{conversation_id: "conv-atmost-once", content: "at-most-once test"}
      })

    assert {:ok, approval} = Governance.request_approval(proposal, enqueue_fn: capture)
    assert {:ok, _} = Governance.approve(approval.id, "operator_1", enqueue_fn: capture)
    assert :ok = ApprovalResumeWorker.perform(%Oban.Job{args: %{"approval_id" => approval.id}})

    # First perform/1 — calls run/3, writes the note row, sets result_state: :succeeded
    assert :ok =
             ToolExecutionWorker.perform(%Oban.Job{
               attempt: 1,
               max_attempts: 3,
               args: %{"approval_id" => approval.id}
             })

    # REPO-UNAVAILABLE: assertions below only pass under mix test.integration
    assert Repo.get!(ToolApproval, approval.id).status == :executed
    assert Repo.get!(ToolProposal, proposal.id).result_state == :succeeded
    assert Repo.aggregate(Message, :count) == 1

    # Second perform/1 with identical args — must be a no-op (LAYER-2 terminal guard)
    assert :ok =
             ToolExecutionWorker.perform(%Oban.Job{
               attempt: 2,
               max_attempts: 3,
               args: %{"approval_id" => approval.id}
             })

    # Still only one message row — run/3 was NOT called a second time
    assert Repo.aggregate(Message, :count) == 1
    assert Repo.get!(ToolApproval, approval.id).status == :executed
  end

  # ---------------------------------------------------------------------------
  # terminal-guard no-op: second perform/1 after :executed does NOT change status
  # and does NOT append a new note row.
  #
  # Distinct from the "replaying :executed approval" test in plan 01: that test
  # uses LAYER-1 (status check); this test confirms the proposal.result_state
  # LAYER-2 guard independently.  We set result_state: :succeeded via a successful
  # first execution and then verify the second call is a strict no-op.
  #
  # REPO-UNAVAILABLE: Repo.get! and Repo.aggregate require a Postgres round-trip.
  # ---------------------------------------------------------------------------

  test "terminal-guard no-op: :executed approval second perform/1 leaves status :executed and no new row" do
    test_pid = self()

    capture = fn job ->
      send(test_pid, {:enqueued, job})
      {:ok, job}
    end

    proposal =
      proposal_fixture(%{
        tool_ref: Atom.to_string(NoteWriteTool),
        approval_mode: :requires_approval,
        scope_snapshot: %{scopes: []},
        input_snapshot: %{conversation_id: "conv-terminal-guard", content: "terminal guard test"}
      })

    assert {:ok, approval} = Governance.request_approval(proposal, enqueue_fn: capture)
    assert {:ok, _} = Governance.approve(approval.id, "operator_1", enqueue_fn: capture)
    assert :ok = ApprovalResumeWorker.perform(%Oban.Job{args: %{"approval_id" => approval.id}})

    # Execute successfully — transitions to :executed
    assert :ok =
             ToolExecutionWorker.perform(%Oban.Job{
               attempt: 1,
               max_attempts: 3,
               args: %{"approval_id" => approval.id}
             })

    # REPO-UNAVAILABLE: assertions below only pass under mix test.integration
    approval_after_first = Repo.get!(ToolApproval, approval.id)
    assert approval_after_first.status == :executed

    # Second perform/1 — LAYER-1 guard: approval.status != :execution_pending → no-op
    assert :ok =
             ToolExecutionWorker.perform(%Oban.Job{
               attempt: 2,
               max_attempts: 3,
               args: %{"approval_id" => approval.id}
             })

    approval_after_second = Repo.get!(ToolApproval, approval.id)
    assert approval_after_second.status == :executed
    assert Repo.aggregate(Message, :count) == 1
  end

  # ---------------------------------------------------------------------------
  # Oban unique enqueue: the worker is configured with
  #   unique: [period: :infinity, fields: [:worker, :args], keys: [:approval_id]]
  # This means Oban will reject a second enqueue for the same approval_id.
  #
  # We assert the worker module's __opts__ carry the unique configuration.
  # The live queue-count leg requires a running Oban instance and is marked
  # REPO-UNAVAILABLE below.
  # ---------------------------------------------------------------------------

  test "Oban unique opts are configured on ToolExecutionWorker (no duplicate enqueue)" do
    # Assert unique configuration — headless, no DB required
    opts = ToolExecutionWorker.__opts__()
    unique_opts = Keyword.get(opts, :unique)

    assert unique_opts != nil,
           "expected ToolExecutionWorker to have unique: [...] opts configured"

    assert Keyword.get(unique_opts, :period) == :infinity,
           "expected unique period: :infinity (at-most-once, no expiry)"

    assert :approval_id in Keyword.get(unique_opts, :keys, []),
           "expected unique keys: [:approval_id] so a second enqueue for the same approval is rejected"

    # REPO-UNAVAILABLE: the live queue-count assertion below only passes under
    # mix test.integration with a running Oban instance.
    # assert Oban.Job |> where([j], j.worker == "Cairnloop.Workers.ToolExecutionWorker"
    #   and j.args["approval_id"] == ^approval_id) |> Repo.aggregate(:count) == 1
  end

  # ---------------------------------------------------------------------------
  # Attempt increment: inline FailOnceTool whose run/3 returns {:error, :db_hiccup}
  # on the first call. After perform/1 with attempt: 1 (< max_attempts: 3):
  #   - proposal.attempt is incremented to 2
  #   - :execution_attempt_failed event is in the trail
  #   - perform/1 returns {:error, reason} so Oban will retry
  #
  # REPO-UNAVAILABLE: Repo.get! and Governance.list_events require Postgres.
  # ---------------------------------------------------------------------------

  test "transient failure: attempt < max_attempts increments attempt and emits :execution_attempt_failed" do
    test_pid = self()

    capture = fn job ->
      send(test_pid, {:enqueued, job})
      {:ok, job}
    end

    proposal =
      proposal_fixture(%{
        tool_ref: Atom.to_string(FailOnceTool),
        approval_mode: :requires_approval,
        scope_snapshot: %{scopes: []},
        input_snapshot: %{conversation_id: "conv-transient"}
      })

    assert {:ok, approval} = Governance.request_approval(proposal, enqueue_fn: capture)
    assert {:ok, _} = Governance.approve(approval.id, "operator_1", enqueue_fn: capture)
    assert :ok = ApprovalResumeWorker.perform(%Oban.Job{args: %{"approval_id" => approval.id}})

    # Transient failure: attempt 1 < max_attempts 3 → {:error, _} so Oban retries
    result =
      ToolExecutionWorker.perform(%Oban.Job{
        attempt: 1,
        max_attempts: 3,
        args: %{"approval_id" => approval.id}
      })

    assert {:error, _reason} = result

    # REPO-UNAVAILABLE: assertions below only pass under mix test.integration
    updated_proposal = Repo.get!(ToolProposal, proposal.id)
    # attempt was incremented inside the co-commit (from initial 0 to 1+1=2)
    assert updated_proposal.attempt == 2

    event_types = proposal.id |> Governance.list_events() |> Enum.map(& &1.event_type)
    assert :execution_attempt_failed in event_types
  end

  # ---------------------------------------------------------------------------
  # InternalNote.run/3 idempotency: two run/3 calls with the same
  # :run_idempotency_key produce ONE row and the second returns
  # {:ok, %{idempotent: true}} (D16-05, T-16-01).
  #
  # REPO-UNAVAILABLE: Repo.aggregate and the run_key column lookup require Postgres.
  # ---------------------------------------------------------------------------

  test "InternalNote.run/3 idempotency: same run_key yields one row, second call returns idempotent: true" do
    alias Cairnloop.Tools.InternalNote

    run_key = "test-run-key-idempotent-#{System.unique_integer([:positive])}"
    context = %{run_idempotency_key: run_key}

    note_struct =
      struct(InternalNote, %{conversation_id: "conv-idem", content: "idempotent note"})

    # REPO-UNAVAILABLE: assertions below only pass under mix test.integration

    # First call — inserts the row, returns {:ok, %{message_id: id}}
    assert {:ok, first_result} = InternalNote.run(note_struct, "operator_1", context)
    assert Map.has_key?(first_result, :message_id)
    assert Repo.aggregate(Message, :count) == 1

    # Second call with same run_key — existence check finds the row, returns idempotent ok
    assert {:ok, second_result} = InternalNote.run(note_struct, "operator_1", context)
    assert second_result == %{idempotent: true, note: "already written"}

    # Still only one message row — no second insert
    assert Repo.aggregate(Message, :count) == 1
  end

  # ---------------------------------------------------------------------------
  # Transient-then-success: a second perform/1 (simulating Oban retry) succeeds
  # AFTER a first perform/1 that returned {:error, reason}. This confirms that
  # the per-attempt run key does NOT block the retry: the new attempt gets a
  # fresh key derived from the incremented attempt number.
  #
  # Uses FailOnceTool which returns {:error, :db_hiccup} on first call then
  # {:ok, %{retried: true}} on subsequent calls.
  #
  # REPO-UNAVAILABLE: Repo.get! and Repo.aggregate require Postgres.
  # ---------------------------------------------------------------------------

  test "transient-then-success: retry succeeds after transient failure; per-attempt key does not block" do
    test_pid = self()

    capture = fn job ->
      send(test_pid, {:enqueued, job})
      {:ok, job}
    end

    proposal =
      proposal_fixture(%{
        tool_ref: Atom.to_string(FailOnceTool),
        approval_mode: :requires_approval,
        scope_snapshot: %{scopes: []},
        input_snapshot: %{conversation_id: "conv-retry"}
      })

    assert {:ok, approval} = Governance.request_approval(proposal, enqueue_fn: capture)
    assert {:ok, _} = Governance.approve(approval.id, "operator_1", enqueue_fn: capture)
    assert :ok = ApprovalResumeWorker.perform(%Oban.Job{args: %{"approval_id" => approval.id}})

    # First attempt — FailOnceTool returns {:error, :db_hiccup} → {:error, _} returned
    assert {:error, _reason} =
             ToolExecutionWorker.perform(%Oban.Job{
               attempt: 1,
               max_attempts: 3,
               args: %{"approval_id" => approval.id}
             })

    # REPO-UNAVAILABLE: assertions below only pass under mix test.integration

    # After first failure, approval is still :execution_pending (transient, not terminal)
    # and proposal.attempt has been incremented (the co-commit inside handle_transient_failure)
    updated_proposal = Repo.get!(ToolProposal, proposal.id)
    assert updated_proposal.attempt == 2

    # Reset approval status to :execution_pending to simulate Oban re-queuing the job
    # (In real Oban, the job would be retried and the approval stays :execution_pending)
    # We need to manually transition back to :execution_pending for the retry test
    Repo.update!(
      Ecto.Changeset.change(Repo.get!(ToolApproval, approval.id), %{status: :execution_pending})
    )

    # Second attempt (Oban retry) — FailOnceTool now returns {:ok, %{retried: true}}
    # The per-attempt key for attempt 2 differs from attempt 1 — retry is NOT blocked
    assert :ok =
             ToolExecutionWorker.perform(%Oban.Job{
               attempt: 2,
               max_attempts: 3,
               args: %{"approval_id" => approval.id}
             })

    # Approval is now :executed (success)
    assert Repo.get!(ToolApproval, approval.id).status == :executed
    assert Repo.get!(ToolProposal, proposal.id).result_state == :succeeded
  end
end
